### PR TITLE
Merge upstream 2025-03-09

### PR DESCRIPTION
**Pull request by mnutt**

### CODE REVIEW

**Comment by Tatsh** [comment]
Do you know if this fixes support with Qt 6.9.1?

**Comment by Tatsh** [comment]
> Do you know if this fixes support with Qt 6.9.1?

No it does not. Fails at final link stage:

```
/usr/lib/gcc/x86_64-pc-linux-gnu/15/../../../../x86_64-pc-linux-gnu/bin/ld: Source/WebKitLegacy/CMakeFiles/WebKitWidgets.dir/qt/WidgetSupport/InitWebKitQt.cpp.o: in function `WebKit::initializeWebKitWidgets()':
/var/tmp/portage/dev-qt/qtwebkit-6.212_p20241223/work/webkit-fc6059b2fd73f5d47c6c7dc30409bb5cb3a4ca97/Source/WebKitLegacy/qt/WidgetSupport/InitWebKitQt.cpp:39:(.text._ZN6WebKit23initializeWebKitWidgetsEv+0x75): undefined reference to `WebKit::setWebKitWidgetsInitCallback(WebCore::QStyleFacade* (*)())'
/usr/lib/gcc/x86_64-pc-linux-gnu/15/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/dev-qt/qtwebkit-6.212_p20241223/work/webkit-fc6059b2fd73f5d47c6c7dc30409bb5cb3a4ca97/Source/WebKitLegacy/qt/WidgetSupport/InitWebKitQt.cpp:40:(.text._ZN6WebKit23initializeWebKitWidgetsEv+0x7a): undefined reference to `WebKit::initializeWebKitQt()'
/usr/lib/gcc/x86_64-pc-linux-gnu/15/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/dev-qt/qtwebkit-6.212_p20241223/work/webkit-fc6059b2fd73f5d47c6c7dc30409bb5cb3a4ca97/Source/WebKitLegacy/qt/WidgetSupport/InitWebKitQt.cpp:44:(.text._ZN6WebKit23initializeWebKitWidgetsEv+0xa8): undefined reference to `WebKit::setImagePlatformResource(char const*, QPixmap const&)'
/usr/lib/gcc/x86_64-pc-linux-gnu/15/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/dev-qt/qtwebkit-6.212_p20241223/work/webkit-fc6059b2fd73f5d47c6c7dc30409bb5cb3a4ca97/Source/WebKitLegacy/qt/WidgetSupport/InitWebKitQt.cpp:46:(.text._ZN6WebKit23initializeWebKitWidgetsEv+0xde): undefined reference to `WebKit::setImagePlatformResource(char const*, QPixmap const&)'
/usr/lib/gcc/x86_64-pc-linux-gnu/15/../../../../x86_64-pc-linux-gnu/bin/ld: lib/libQt6WebKitWidgets.so.6.212.0: protected symbol `_ZN6WebKit18initializeWebKitQtEv' isn't defined
/usr/lib/gcc/x86_64-pc-linux-gnu/15/../../../../x86_64-pc-linux-gnu/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
```

**Comment by mnutt** [comment]
@Tatsh are you using any build flags or anything? I got it to successfully build on 6.9.1 using this:

https://gist.github.com/mnutt/2bef67e6bdc5ea511af504840e11ba6a

**Comment by Tatsh** [comment]
Flags are here: https://github.com/Tatsh/tatsh-overlay/blob/master/dev-qt/qtwebkit/qtwebkit-6.212_p20241223.ebuild#L45 and was building with build type Release. LTO should be off unless it is somehow getting turned on in a different way by qtwebkit itself. I do build with `-O2 -ggdb -march=native -mtune=native -pipe` but I do not think this should be an issue.

**Comment by Tatsh** [comment]
Retrying now with SHA `fc6059b2fd73f5d47c6c7dc30409bb5cb3a4ca97` because I do not have a full build log from the last time.

**Comment by mnutt** [comment]
Actually could you try against https://github.com/movableink/webkit/pull/48 ? It is 3 months newer and has a number of qt-6.9-related fixes.

**Comment by Tatsh** [comment]
Could you share a build log in any case? What I found is that the build system is enabling `-Wl,--no-undefined` but I am wondering if you are seeing this in the Ubuntu case? Also what is the [`-H.`](https://gist.github.com/mnutt/2bef67e6bdc5ea511af504840e11ba6a#file-build-sh-L6) is supposed to do?

**Comment by Tatsh** [comment]
Here's the link command expanded:

```
/usr/bin/c++ \
-fPIC \
-fvisibility=hidden \
-fvisibility-inlines-hidden \
-fdiagnostics-color=always \
-Wextra \
-Wall \
-pipe \
-fmax-errors=20 \
-Wno-odr \
-Wno-stringop-overread \
-Wno-stringop-overflow \
-Wno-nonnull \
-Wno-array-bounds \
-Wno-expansion-to-defined \
-Wno-noexcept-type \
-Wno-subobject-linkage \
-Wno-psabi \
-Wno-misleading-indentation \
-Wno-maybe-uninitialized \
-Wundef \
-Wpointer-arith \
-Wmissing-format-attribute \
-Wformat-security \
-Wcast-align \
-Wno-tautological-compare \
-fasynchronous-unwind-tables \
-fno-strict-aliasing \
-fno-exceptions \
-fno-rtti \
-fcoroutines \
-ffunction-sections \
-fdata-sections \
-g \
-Wl,--gc-sections \
-Wl,--disable-new-dtags \
-Wl,--version-script,/home/tatsh/dev/webkit/build/QtWebKitWidgets.version \
-Wl,--dependency-file=Source/WebKitLegacy/CMakeFiles/WebKitWidgets.dir/link.d \
-shared \
-Wl,-soname,libQt6WebKitWidgets.so.6 \
-o \
lib/libQt6WebKitWidgets.so.6.212.0 \
Source/WebKitLegacy/CMakeFiles/WebKitWidgets.dir/WebKitWidgets_autogen/mocs_compilation.cpp.o \
Source/WebKitLegacy/CMakeFiles/WebKitWidgets.dir/qt/WidgetApi/qgraphicswebview.cpp.o \
Source/WebKitLegacy/CMakeFiles/WebKitWidgets.dir/qt/WidgetApi/qwebframe.cpp.o \
Source/WebKitLegacy/CMakeFiles/WebKitWidgets.dir/qt/WidgetApi/qwebinspector.cpp.o \
Source/WebKitLegacy/CMakeFiles/WebKitWidgets.dir/qt/WidgetApi/qwebpage.cpp.o \
Source/WebKitLegacy/CMakeFiles/WebKitWidgets.dir/qt/WidgetApi/qwebpage_p.cpp.o \
Source/WebKitLegacy/CMakeFiles/WebKitWidgets.dir/qt/WidgetApi/qwebview.cpp.o \
Source/WebKitLegacy/CMakeFiles/WebKitWidgets.dir/qt/WidgetApi/qwebviewaccessible.cpp.o \
Source/WebKitLegacy/CMakeFiles/WebKitWidgets.dir/qt/WidgetSupport/InitWebKitQt.cpp.o \
Source/WebKitLegacy/CMakeFiles/WebKitWidgets.dir/qt/WidgetSupport/InspectorClientWebPage.cpp.o \
Source/WebKitLegacy/CMakeFiles/WebKitWidgets.dir/qt/WidgetSupport/PageClientQt.cpp.o \
Source/WebKitLegacy/CMakeFiles/WebKitWidgets.dir/qt/WidgetSupport/QGraphicsWidgetPluginImpl.cpp.o \
Source/WebKitLegacy/CMakeFiles/WebKitWidgets.dir/qt/WidgetSupport/QStyleFacadeImp.cpp.o \
Source/WebKitLegacy/CMakeFiles/WebKitWidgets.dir/qt/WidgetSupport/QWebUndoCommand.cpp.o \
Source/WebKitLegacy/CMakeFiles/WebKitWidgets.dir/qt/WidgetSupport/QWidgetPluginImpl.cpp.o \
Source/WebKitLegacy/CMakeFiles/WebKitWidgets.dir/qt/WidgetSupport/QtFallbackWebPopup.cpp.o \
Source/WebKitLegacy/CMakeFiles/WebKitWidgets.dir/qt/WidgetSupport/QtWebComboBox.cpp.o \
-Wl,-rpath,/home/tatsh/dev/webkit/build/lib: \
/usr/lib64/libQt6Widgets.so.6.9.1 \
lib/libQt6WebKit.so.6.212.0 \
/usr/lib64/libQt6Gui.so.6.9.1 \
/usr/lib64/libGLX.so \
/usr/lib64/libOpenGL.so \
/usr/lib64/libQt6Network.so.6.9.1 \
/usr/lib64/libQt6Core.so.6.9.1
```

Outputs:

```
/usr/lib/gcc/x86_64-pc-linux-gnu/15/../../../../x86_64-pc-linux-gnu/bin/ld: Source/WebKitLegacy/CMakeFiles/WebKitWidgets.dir/qt/WidgetSupport/InitWebKitQt.cpp.o: in function `WebKit::initializeWebKitWidgets()':
/home/tatsh/dev/webkit/Source/WebKitLegacy/qt/WidgetSupport/InitWebKitQt.cpp:39:(.text._ZN6WebKit23initializeWebKitWidgetsEv+0x7f): undefined reference to `WebKit::setWebKitWidgetsInitCallback(WebCore::QStyleFacade* (*)())'
/usr/lib/gcc/x86_64-pc-linux-gnu/15/../../../../x86_64-pc-linux-gnu/bin/ld: /home/tatsh/dev/webkit/Source/WebKitLegacy/qt/WidgetSupport/InitWebKitQt.cpp:40:(.text._ZN6WebKit23initializeWebKitWidgetsEv+0x84): undefined reference to `WebKit::initializeWebKitQt()'
/usr/lib/gcc/x86_64-pc-linux-gnu/15/../../../../x86_64-pc-linux-gnu/bin/ld: /home/tatsh/dev/webkit/Source/WebKitLegacy/qt/WidgetSupport/InitWebKitQt.cpp:44:(.text._ZN6WebKit23initializeWebKitWidgetsEv+0xc6): undefined reference to `WebKit::setImagePlatformResource(char const*, QPixmap const&)'
/usr/lib/gcc/x86_64-pc-linux-gnu/15/../../../../x86_64-pc-linux-gnu/bin/ld: /home/tatsh/dev/webkit/Source/WebKitLegacy/qt/WidgetSupport/InitWebKitQt.cpp:46:(.text._ZN6WebKit23initializeWebKitWidgetsEv+0x114): undefined reference to `WebKit::setImagePlatformResource(char const*, QPixmap const&)'
/usr/lib/gcc/x86_64-pc-linux-gnu/15/../../../../x86_64-pc-linux-gnu/bin/ld: lib/libQt6WebKitWidgets.so.6.212.0: protected symbol `_ZN6WebKit18initializeWebKitQtEv' isn't defined
/usr/lib/gcc/x86_64-pc-linux-gnu/15/../../../../x86_64-pc-linux-gnu/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

When I add `Source/WebKitLegacy/CMakeFiles/WebKitLegacy.dir/qt/WebCoreSupport/InitWebCoreQt.cpp.o` right after the `-o lib/libQt6WebKitWidgets.so.6.212.0`, the command succeeds.

**Comment by Tatsh** [comment]
But the above does require removing `-Wl,--no-undefined`. Otherwise it fails with a different error and it looks like it has to do with more dependencies needed to link:

```
/usr/lib/gcc/x86_64-pc-linux-gnu/15/../../../../x86_64-pc-linux-gnu/bin/ld: Source/WebKitLegacy/CMakeFiles/WebKitWidgets.dir/qt/WebCoreSupport/InitWebCoreQt.cpp.o: in function `WebKit::initializeWebKitQt()':
/home/tatsh/dev/webkit/Source/WebKitLegacy/qt/WebCoreSupport/InitWebCoreQt.cpp:66:(.text._ZN6WebKit18initializeWebKitQtEv+0x24): undefined reference to `WebCore::RenderThemeQStyle::setStyleFactoryFunction(WebCore::QStyleFacade* (*)())'
/usr/lib/gcc/x86_64-pc-linux-gnu/15/../../../../x86_64-pc-linux-gnu/bin/ld: /home/tatsh/dev/webkit/Source/WebKitLegacy/qt/WebCoreSupport/InitWebCoreQt.cpp:67:(.text._ZN6WebKit18initializeWebKitQtEv+0x39): undefined reference to `WebCore::ScrollbarThemeQStyle::ScrollbarThemeQStyle()'
/usr/lib/gcc/x86_64-pc-linux-gnu/15/../../../../x86_64-pc-linux-gnu/bin/ld: /home/tatsh/dev/webkit/Source/WebKitLegacy/qt/WebCoreSupport/InitWebCoreQt.cpp:67:(.text._ZN6WebKit18initializeWebKitQtEv+0x40): undefined reference to `WebCore::RenderThemeQStyle::singleton()'
/usr/lib/gcc/x86_64-pc-linux-gnu/15/../../../../x86_64-pc-linux-gnu/bin/ld: /home/tatsh/dev/webkit/Source/WebKitLegacy/qt/WebCoreSupport/InitWebCoreQt.cpp:67:(.text._ZN6WebKit18initializeWebKitQtEv+0x4b): undefined reference to `WebCore::RenderThemeQt::setCustomTheme(WebCore::RenderTheme& (*)(), WebCore::ScrollbarTheme*)'
/usr/lib/gcc/x86_64-pc-linux-gnu/15/../../../../x86_64-pc-linux-gnu/bin/ld: Source/WebKitLegacy/CMakeFiles/WebKitWidgets.dir/qt/WebCoreSupport/InitWebCoreQt.cpp.o: in function `WebKit::setImagePlatformResource(char const*, QPixmap const&)':
/home/tatsh/dev/webkit/Source/WebKitLegacy/qt/WebCoreSupport/InitWebCoreQt.cpp:73:(.text._ZN6WebKit24setImagePlatformResourceEPKcRK7QPixmap+0x45): undefined reference to `WebCore::Image::setPlatformResource(char const*, QImage const&)'
/usr/lib/gcc/x86_64-pc-linux-gnu/15/../../../../x86_64-pc-linux-gnu/bin/ld: Source/WebKitLegacy/CMakeFiles/WebKitWidgets.dir/qt/WebCoreSupport/InitWebCoreQt.cpp.o: in function `WebCore::initializeWebCoreQt()':
/home/tatsh/dev/webkit/Source/WebKitLegacy/qt/WebCoreSupport/InitWebCoreQt.cpp:93:(.text._ZN7WebCore19initializeWebCoreQtEv+0x6f): undefined reference to `PlatformStrategiesQt::initialize()'
/usr/lib/gcc/x86_64-pc-linux-gnu/15/../../../../x86_64-pc-linux-gnu/bin/ld: /home/tatsh/dev/webkit/Source/WebKitLegacy/qt/WebCoreSupport/InitWebCoreQt.cpp:94:(.text._ZN7WebCore19initializeWebCoreQtEv+0x74): undefined reference to `QtWebElementRuntime::initialize()'
```
